name: Update PubMed Rochester DB

on:
  schedule:
    - cron: "0 0 1 1 *"   # once per year, Jan 1 at midnight UTC
  workflow_dispatch:      # allow manual runs from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run PubMed script
        run: python your_script.py   # <-- replace with your actual script filename

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pubmed_rochester.db
          git commit -m "Update PubMed Rochester DB: $(date -u)" || echo "No changes to commit"
          git push
